title: Researcher
url: "http://svidovich.github.io"
baseurl: "/researcher"

#<<<<<<< HEAD
#=======
# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
#	Samuel Vidovich Resume and Experience!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://svidovich.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
#>>>>>>> 0812791473563b26b904739cecfda142b263c2c6
markdown: kramdown

tracking_id: #

sass:
    style: compressed
    sass_dir: _sass
